export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";

export const SET_LABELS = "SET_LABELS";

export const SET_TYPE_CHECK_REQUEST = "SET_TYPE_CHECK_REQUEST";
export const SET_TYPE_CHECK_SUCCESS = "SET_TYPE_CHECK_SUCCESS";
export const SET_BRAND_CHECK_REQUEST = "SET_BRAND_CHECK_REQUEST";
export const SET_BRAND_CHECK_SUCCESS = "SET_BRAND_CHECK_SUCCESS";
export const SET_RATING_CHECK_REQUEST = "SET_RATING_CHECK_REQUEST ";
export const SET_RATING_CHECK_SUCCESS = "SET_RATING_CHECK_SUCCESS ";
export const SET_PRICERANGE_CHECK_REQUEST = "SET_PRICERANGE_CHECK_REQUEST ";
export const SET_PRICERANGE_CHECK_SUCCESS = "SET_PRICERANGE_CHECK_SUCCESS ";

export const SET_PAGE_REQUEST = "SET_PAGE_REQUEST";
export const SET_PAGE_SUCCESS = "SET_PAGE_SUCCESS";
export const SET_SORT_REQUEST = "SET_SORT_REQUEST";
export const SET_SORT_SUCCESS = "SET_SORT_SUCCESS";
